### ISSUE TITLE
Doesn't compile out of the box with g++ 5.4.0

### ISSUE THREAD

**Issue by rassouly** [Leinnan/i3gs#1]
Hello,
I tried to build your software using cmake 3.5.1 and g++ 5.4.0 and during the compilation, the compiler kept giving errors about c++11 and c++14 stuff. I replaced the "std=c++14" by "std=c++1z" in the CMakeLists.txt and everything worked fine.

**Comment by Leinnan** [comment]
Have you tried "std=c++11" flag?
